version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: deforestation-exploration-db
    hostname: deforestation-exploration-db
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    networks:
      - deforestation-exploration-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  deforestation-exploration-network:
    name: deforestation-exploration-network
