version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: deforestation-exploration-db
    hostname: deforestation-exploration-db
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    networks:
      - deforestation-exploration-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: deforestation-exploration-pgadmin
    hostname: deforestation-exploration-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - deforestation-exploration-pgadmin-data:/var/lib/pgadmin
    ports:
      - "80:80"
    networks:
      - deforestation-exploration-network
    depends_on:
      - postgres

  data-import:
    build: ./deforestation-exploration-data-import
    container_name: deforestation-exploration-data-import
    hostname: deforestation-exploration-data-import
    environment:
      BASE_PATH: /app/datasets
      DB_URL: postgresql://postgres:mysecretpassword@deforestation-exploration-db:5432/postgres
    volumes:
      - ./datasets:/app/datasets
    depends_on:
      - postgres
    networks:
      - deforestation-exploration-network

networks:
  deforestation-exploration-network:
    name: deforestation-exploration-network

volumes:
  deforestation-exploration-pgadmin-data:
    name: deforestation-exploration-pgadmin-data